name: 'notes2rdf'
description: 'Convert notes directory structure to RDF'
inputs:
  query:
    description: 'Root directory of notes'
    required: true
  graph:
    description: 'Graph represented as an RDF file'
  format:
    description: 'Format of the RDF file'
    default: 'turtle'
  output-file:
    description: 'Output file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.query }}
    - ${{ inputs.graph }}
    - ${{ inputs.format }}
    - ${{ inputs.output-file }}
    